# Generated by Django 6.1.1 on 2026-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Укажите стоимость курса в рублях",
                max_digits=10,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="ID цены в Stripe",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="ID продукта в Stripe",
            ),
        ),
    ]
